updated required python version
Azure-Samples/communication-services-python-quickstarts pull request #21
Opened 2022-11-28 09:46 UTC by ostoliarova-msft

## Purpose
Update required python versions as support for python 2.7 and 3.6 ended.

[User Story 2974554](https://skype.visualstudio.com/SPOOL/_workitems/edit/2974554): [Docs] Update public docs regarding the dropping support of 2.7 and 3.6 versions
## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-11-28 17:01 UTC, petrsvihlik approved these changes

2022-11-29 06:23 UTC, AikoBB requested changes
Pls update the following references as well:

- [get-relay-configuration](https://github.com/Azure-Samples/communication-services-python-quickstarts/blob/main/get-relay-configuration-quickstart/README.md#prerequisites)
- [main readme](https://github.com/Azure-Samples/communication-services-python-quickstarts/blob/main/README.md#prerequisites)
- [add-chat](https://github.com/Azure-Samples/communication-services-python-quickstarts/tree/main/add-chat#prerequisites)

2022-11-29 08:02 UTC, ostoliarova-msft commented
@AikoBB thanks for spotting these! I updated.

2022-11-29 08:12 UTC, AikoBB approved these changes
@ddematheu2 @lei-msft this PR is ready for review and merge

2022-11-30 22:08 UTC, moirf approved these changes

2022-12-01 07:06 UTC, merged